apiVersion: v1
kind: Service
metadata:
  name: community-be-svc
spec:
  type: NodePort
  selector:
    app: community-be
  ports:
    - name: http
      protocol: TCP
      port: 80               # 서비스 내부 포트 (Ingress가 여기로 보냄)
      targetPort: 3000       # [체크] 파드 내부의 3000번으로 연결
      nodePort: 30030        # [체크] 외부에서 접근할 NodePort